# Generated by Django 3.2.8 on 2021-11-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=500)),
                ('opt1', models.CharField(max_length=50)),
                ('opt2', models.CharField(max_length=50)),
                ('opt3', models.CharField(max_length=50)),
                ('opt4', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
